Repository F5Networks/k8s-bigip-ctlr, pull requests merged in 2019-09, with the labels that each got.

#1025 Add funtionality to make developer builds
  Makefile
  build-tools/golang/0001-Enable-AS3-Declaration-logging.patch
Labels: regression-not-required

#1015 Support Path based Routing for Reencrypt routes
  docs/RELEASE-NOTES.rst
  pkg/appmanager/appManager_test.go
  pkg/appmanager/routing.go
Labels: regression-passed

#1020 Alternate backend supports for openshift routes
  pkg/appmanager/as3Manager.go
  pkg/appmanager/resourceConfig.go
  pkg/appmanager/routing.go
Labels: regression-passed

#1012 Fix AS3 Configmap cleanup
  pkg/appmanager/appManager.go
  pkg/appmanager/as3Manager.go
Labels: regression-pending

#1018 Response body formate refactored
  pkg/appmanager/as3Manager.go
Labels: regression-passed

#1029 as3 schema validation using latest schema
  cmd/k8s-bigip-ctlr/main.go
  pkg/appmanager/appManager.go
  pkg/appmanager/as3Manager.go
Labels: regression-passed

#1026 route-vserver-addr is required when mange-routes is enabled
  cmd/k8s-bigip-ctlr/main.go
  docs/RELEASE-NOTES.rst
Labels: bug, regression-passed

#1017 Log INFO messages in Standard Output
  docs/RELEASE-NOTES.rst
  pkg/vlogger/console/log_console.go
Labels: regression-passed

#1030 Add Support for WAF Policy reference in Route
  pkg/appmanager/appManager.go
  pkg/appmanager/as3Manager.go
  pkg/appmanager/as3Types.go
  pkg/appmanager/types.go
Labels: regression-passed
