Repository F5Networks/k8s-bigip-ctlr, pull requests merged in 2019-10, with the labels that each got.

#1032 Update Route admitted status in OpenShift 3.11 GUI
  docs/RELEASE-NOTES.rst
  docs/conf.py
  pkg/appmanager/appManager.go
  pkg/appmanager/as3Manager.go
Labels: enhancement, regression-passed

#1048 Add next version
  next-version.txt
Labels: regression-not-required

#1049 Add next patch version
  next-version.txt
Labels: regression-not-required

#1054 Fix applying WAF to root of a domain
  docs/RELEASE-NOTES.rst
  pkg/appmanager/as3Manager.go
Labels: 1.11.1, regression-passed

#1057 Fix Issue with WAF Policy for routes in Multiple Namespaces
  docs/RELEASE-NOTES.rst
  pkg/appmanager/appManager.go
  pkg/appmanager/as3Manager.go
  pkg/appmanager/types.go
Labels: regression-passed

#1055 OCP 3.11 and 4.1 - Fix for Route Admit statuses
  docs/RELEASE-NOTES.rst
  pkg/appmanager/appManager.go
  pkg/appmanager/as3Manager.go
Labels: regression-pending
