Repository F5Networks/k8s-bigip-ctlr, pull requests merged in 2020-01, with the labels that each got.

#1123 Refactor Code that posts AS3 Config to BIG-IP
  cmd/k8s-bigip-ctlr/main.go
  docs/RELEASE-NOTES.rst
  pkg/appmanager/appManager.go
  pkg/appmanager/appManager_test.go
  pkg/appmanager/as3Manager.go
  pkg/appmanager/as3Manager_test.go
  pkg/appmanager/as3Types.go
  pkg/appmanager/as3Utils.go
  pkg/appmanager/outputConfig.go
  pkg/appmanager/validateResources.go
  pkg/postmanager/postManager.go
Labels: regression-passed

#1047 Add Feature Tenant Filter
  cmd/k8s-bigip-ctlr/main.go
  docs/RELEASE-NOTES.rst
  pkg/appmanager/appManager.go
  pkg/appmanager/as3Manager.go
  pkg/postmanager/postManager.go
Labels: regression-passed

#1147 Fix CIS allows userDefinedConfigmap with CIS managed Partition as Tenant
  docs/RELEASE-NOTES.rst
  pkg/appmanager/as3Manager.go
Labels: regression-passed

#1148 Enhance httpsredirect Irule to support childpaths
  pkg/appmanager/routing.go
Labels: regression-pending

#1157 Fix issues for Edge route with InsecureEdgeTerminationPolicy:Redirect
  pkg/appmanager/routing.go
Labels: regression-passed

#1163 Add next version
  next-version.txt
Labels: regression-not-required

#1164 Add next version 1.13.1
  next-version.txt
Labels: regression-not-required
