Repository F5Networks/k8s-bigip-ctlr, pull requests merged in 2020-03, with the labels that each got.

#1194 Fix virtual-server.f5.com/http-port ingress annotation issue with agent AS3
  pkg/appmanager/as3Manager.go
  pkg/appmanager/as3Utils.go
Labels: regression-pending

#1195 Fix balance annotation update issue for routes and ingresses
  pkg/appmanager/resourceConfig.go
Labels: regression-pending

#1188 fix httpsredirect for ingress with noHostSpec
  docs/RELEASE-NOTES.rst
  pkg/appmanager/routing.go
Labels: regression-passed

#1207 Update next patch version to 1.14.1
  next-version.txt
Labels: regression-not-required

#1206 Update next version to 2.0
  next-version.txt
Labels: regression-not-required
